name: container-toolkit

on:
  # Set schedule to run every 24 hours
  #schedule:
  #  - cron: '0 */24 * * *'

  # Allow to trigger action manually
  workflow_dispatch:

jobs:
  check_and_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Check versions
      run: |
        # Grab latest release from official repostiory and latest release version from this repostiory
        LATEST_TOOLKIT="$(curl -u ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} -s https://api.github.com/repos/NVIDIA/nvidia-container-toolkit/tags | jq -r '.[] | select(.name | test("-(rc|beta|alpha)"; "i") | not) | .name' | sort -V | tail -1 | sed 's/^v//')"
        CURRENT_TOOLKIT="$(curl -u ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} -s https://api.github.com/repos/${{ github.repository_owner }}/mos-nvidia-container-toolkit/releases/latest | jq -r '.tag_name' | sed 's/^v//')"

        # Check if one of the versions is empty
        if ! echo "${LATEST_TOOLKIT}" | grep -qE '^\b[0-9]+(\.[0-9]+)*\b$'; then
          echo "Can't get versions"
          exit 1
        fi
        if ! echo "${CURRENT_TOOLKIT}" | grep -qE '^\b[0-9]+(\.[0-9]+)*\b$'; then
          echo "Can't get versions"
          #exit 1
        fi

        # Check versions
        if [ "${LATEST_TOOLKIT}" != "${CURRENT_TOOLKIT}" ]; then
          echo "CREATE_RELEASE=true" >> $GITHUB_ENV
          echo "TOOLKIT_VERSION=${LATEST_TOOLKIT}" >> $GITHUB_ENV
        else
          echo "nvidia-container-toolkit v${CURRENT_TOOLKIT} up to date!"
          echo "CREATE_RELEASE=false" >> $GITHUB_ENV
        fi

    - name: Log in to GitHub Container Registry
      if: env.CREATE_RELEASE == 'true'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Run Docker container and build nvidia-container-toolkit
      if: env.CREATE_RELEASE == 'true'
      run: |
        docker run --rm \
          -v ${{ github.workspace }}/output:/tmp \
          -e TOOLKIT_VERSION=${TOOLKIT_VERSION} \
          ghcr.io/${{ github.repository_owner }}/mos-nvidia-container-toolkit:buster

    - name: Create Release
      if: env.CREATE_RELEASE == 'true' && success()
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.TOOLKIT_VERSION }}
        release_name: "nvidia-container-toolkit ${{ env.TOOLKIT_VERSION }}"
        body: |
          nvidia-container-toolkit ${{ env.TOOLKIT_VERSION }} for MOS
        draft: false
        prerelease: false

    - name: Upload deb to Release
      if: env.CREATE_RELEASE == 'true' && success()
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./output/nvidia-container-toolkit_${{ env.TOOLKIT_VERSION }}-1+mos_amd64.deb
        asset_name: nvidia-container-toolkit_${{ env.TOOLKIT_VERSION }}-1+mos_amd64.deb
        asset_content_type: application/vnd.debian.binary-package

    - name: Upload md5 to Release
      if: env.CREATE_RELEASE == 'true' && success()
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./output/nvidia-container-toolkit_${{ env.TOOLKIT_VERSION }}-1+mos_amd64.deb.md5
        asset_name: nvidia-container-toolkit_${{ env.TOOLKIT_VERSION }}-1+mos_amd64.deb.md5
        asset_content_type: text/plain
